### ISSUE TITLE
Recursive doesn't work as expected 

### ISSUE THREAD

**Issue by RezaRahmati** [slevithan/xregexp#272] opened 2019-09-06 01:45 UTC
I have below code

```
const XRegExp = require('xregexp');

const str2 = `messages: {something:'val', x: { y } }`;

const arr2 = XRegExp.matchRecursive(str2, 'messages: {', '}', 'gi');

console.log(arr2);


const str = `{ prop1: 'val1', prop2:{ prop3: 'val3' , messages: {something:'val'} messages: { something:'val2', x : {x : 1, y : 5} } prop4 : 'val4' } }`;

const arr = XRegExp.matchRecursive(str, 'messages: {', '}', 'gi');

console.log(arr);
```
for both I receive Error: Unbalanced delimiter found in string at Function.XRegExp.matchRecursive 

I expect to find all `messages: { ... }`

Please take a look at [https://repl.it/@RezaRahmati/xregexp](https://repl.it/@RezaRahmati/xregexp)

**Comment by slevithan** [comment] 2019-11-08 23:25
The issue is that, to use your first example subject string, there is only one opening delimiter in the string (“messages: {“) and two closing delimiters (“}”). Although I would definitely like to update XRegExp.matchRecursive to provide an option to support subject strings with non-balanced delimiters, that just hasn’t been built yet (see #96 for details).

Changing the opening delimiter to “messages: {|{“ should fix this and work as you expect. You could then check your matches to see whether they start with “messages: {“ or just “{“, and discard the latter.

**Closed by slevithan** 2019-11-08 23:25 UTC
