### ISSUE TITLE
The performance is awful.

### ISSUE THREAD

**Issue by steffenw** [slevithan/xregexp#79] opened 2014-10-23 05:41 UTC
I tested that package but the performance during compiling the regex to a real JavaScript regex was awful. The website need lots of time for 1 time run of that regex. Chrome needs about 30 seconds. Now with the real JavaScript regex the run was shorter than a click. So I removed xregexp a quick as possible.

The idea is good because I know very good readable regexes only from Perl. That was the reason to try that.

The regex I wrote was:
```
var keyRegexPart
    = jQuery.map(
        Object.keys(replaceMap),
        function (key, index) {
            return XRegExp.escape(key);
        }
    )
    .join('|');
var placeholderRegex = XRegExp(
    '(?<placeholder>                            # full match \n\
        \\{                                     # {          \n\
            (?<name>                            # name       \n'
    + keyRegexPart
    +       ')                                               \n\
            (?: [ ]* [:] (?<attr> [^:\\}]+ ) )? # :attr_name \n\
        \\}                                     # }          \n\
    )',
    'xmsg'
);
```

**Comment by chocolateboy** [comment] 2015-02-22 12:49
FWIW, [this jsperf benchmark](http://jsperf.com/regex-vs-xregexpsss) appears to confirm that there's a serious performance issue/regression in 3.0.0-pre.

**Comment by chocolateboy** [comment] 2015-02-22 13:11
Never mind. The issue goes away (for me) if the `cache` call is [removed from the loop](http://jsperf.com/regex-vs-xregexpsss/3).

**Comment by slevithan** [comment] 2015-06-04 05:14
Closing since @steffenw hasn't confirmed the version and I can't repro. The provided regex compiles near instantly (although I don't know what string was held by the `keyRegexPart` variable, and if this was a very long string it would take longer on the first compilation). The compiled regex will then run as fast as a native regex (since it is compiled to a native regex).

**Closed by slevithan** 2015-06-04 05:14 UTC

**Comment by slevithan** [comment] 2015-09-02 20:05
Note that the `cache` method (and many other XRegExp operations) have been made a lot faster in the the most recent versions of V3.0.0-pre.
