### ISSUE TITLE
Hangs when loading module in IE11 - with core-js 3.6.0 or newer, with and without babel sticky-regex polyfill

### ISSUE THREAD

**Issue by perbergland** [slevithan/xregexp#300] opened 2020-09-10 08:48 UTC
v 4.3.0

With core-js 3.6.0 (and newer up to 3.6.5), when loading the module, the call to `const parts = XRegExp.union` hangs and never returns. core-js 3.6.0 introduced new compatibility stuff for sticky so maybe that’s the core problem?

https://github.com/slevithan/xregexp/blob/95eeebeb8fac8754d54eafe2b4743661ac1cf028/src/addons/build.js#L10

**Comment by perbergland** [comment] 2020-09-10 09:39
I reproduced the error in IE11 also with an empty next.js project with and without regex sticky polyfills by just adding `import xregexp from "xregexp"` to index.js.

To disable the default polyfill, I used this .babelrc

```
{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": {
          "exclude": ["@babel/plugin-transform-sticky-regex"]
        }
      }
    ]
  ]
}
```

This is the loop that never exits because token is an empty string:

![Screenshot 2020-09-10 kl  11 30 39](https://user-images.githubusercontent.com/2690254/92712419-e9e59e80-f359-11ea-8d3f-f027fdc36838.png)

**Comment by perbergland** [comment] 2020-09-10 12:03
repro repo

https://github.com/perbergland/xregexp-repro-issue-300

**Comment by perbergland** [comment] 2020-09-11 11:10
@slevithan is this something you could take a look at? I don’t quite grasp the purpose of the code that hangs

**Comment by perbergland** [comment] 2020-09-18 06:31
@josephfrazier any chance you could take a peek?

**Comment by slevithan** [comment] 2020-09-21 21:06
@perbergland The line of code you highlighted is just concatenating two different regexes together, and separating them with an “or” (`|`) operator. The resulting regex is assigned the name `parts`. This concatenation is merely done so that the `subParts` half of the regex can be reused independently elsewhere in the XRegExp.build file/addon.

A couple asides:
* In case it’s helpful to understand the `subParts` regex, it matches any of the following regex syntax parts, in order:
  1. The opening paren `(` of an unnamed capturing group.
  2. A numbered backreference — e.g. `\2` or `18`.
  3. Any escaped character — e.g. `\[` or `\n`.
  4. Any (complete) character class — e.g. `[^\w$]`.
* The `XRegExp.union` function used to concatenate the regexes here can be used for fancy stuff like rewriting backreference numbers within concatenated regexes, but that’s not relevant in this case.

Some potential fixes and workarounds:

* Ideally: Identify and fix/address the issue within `XRegExp.union`, starting by finding a reduced error case. The regexes fed to `union` in the line you’ve pointed out are probably needlessly complex for triggering whatever the issue is in IE 11 with core-js 3.6.0+.
* Use XRegExp without the XRegExp.build addon.
* Update the XRegExp.build addon to not use `XRegExp.union` there:

```js
const subParts = /(\()(?!\?)|\\([1-9]\d*)|\\[\s\S]|\[(?:[^\\\]]|\\[\s\S])*\]/g;
const parts = /\({{([\w$]+)}}\)|{{([\w$]+)}}|(\()(?!\?)|\\([1-9]\d*)|\\[\s\S]|\[(?:[^\\\]]|\\[\s\S])*\]/g;
```

**Comment by perbergland** [comment] 2020-09-27 20:08
Not sure I understand what you mean, but I ended up removing the dependency on xregexp from my app to fix the IE incompatibility. Feel free to close the issue, I don't care anymore.

**Comment by NathanAB** [comment] 2020-10-21 18:08
@perbergland just wanna let you know this issue is totally ruining my day right now. You're not alone 😅 

IE11 hangs and is completely broken just by including this library as stated.

**Comment by slevithan** [comment] 2020-10-27 00:44
I've starting looking into this. Thanks for the repro repo @perbergland. So far I've learned the issue in IE11 is not being triggered by the identified line per se. It is any invocation of the `XRegExp` constructor with core-js 3.6.0+. E.g. `XRegExp('testregex')` will trigger the same infinite loop.

**Comment by slevithan** [comment] 2020-10-27 21:48
I've added a fix for this in https://github.com/slevithan/xregexp/commit/bece2eb1b4e4206ac07c62d75c457effd93eb491

> core-js 3.6.0 introduced new compatibility stuff for sticky so maybe that’s the core problem?

That was indeed the problem. The core-js 3.6.0 sticky polyfill appears to be partially broken or incomplete. I've added a check for incorrect handling of sticky, and made XRegExp treat the `y` (sticky) flag as unsupported in that case.

**Closed by slevithan** 2020-10-27 21:48 UTC

**Comment by slevithan** [comment] 2020-10-29 21:45
Fix published in v4.4.0.

**Comment by johnzhou721** [comment] 2026-03-16 16:30
> repro repo
> 
> https://github.com/perbergland/xregexp-repro-issue-300

@perbergland I'm interested in fixing this on the core-js side.  Does this repro only use core-js instead of using xregexp?  Also the link is a 404 now, do you still have the repo by chance?

**Comment by perbergland** [comment] 2026-03-16 17:55
Sorry, this has been archived and lost in the annals of time

**Comment by johnzhou721** [comment] 2026-03-16 18:08
Alright... from the fact that the pattern in the debugger image has a | in it, I guess it may be fixed by https://github.com/zloirock/core-js/commit/cf0ad5db01a7516239e5f7d1d880a3a055a592af

Can we remove the workaround and test on the next version of core-js?

**Comment by slevithan** [comment] 2026-03-16 20:58
@johnzhou721 XRegExp is in maintenance mode. You're welcome to test it, and any PRs are welcome. But the workaround would still be needed for people running XRegExp with older core-js.

**Comment by johnzhou721** [comment] 2026-03-16 21:27
@slevithan Good.  Also new core-js just cut.  I just realized don't have the bandwidth for extensive testing, sorry.
