### ISSUE TITLE
`\p{Script=Katakana}` vs `\p{Katakana}`

### ISSUE THREAD

**Issue by bluelovers** [slevithan/xregexp#246] opened 2018-05-06 09:38 UTC
xregexp style is `\p{Katakana}`

but nodejs is `\p{Script=Katakana}`

when input will get `Unknown Unicode token \p{Script=Katakana}`

maybe need allow use `Script=xxx`

**Comment by mathiasbynens** [comment] 2018-05-06 22:50
Duplicate of #225.

**Closed by mathiasbynens** 2018-05-06 22:50 UTC
