### ISSUE TITLE
Using named group object is difficult

### ISSUE THREAD

**Issue by Ciantic** [slevithan/xregexp#45] opened 2012-11-28 20:23 UTC
I need to loop over the named parameters after executing, seems to be pretty problematic. Why are you augmenting the array with properties? Shouldn't you provide a way to give access to clean named object?

Taken regex `"(?<type>[a-z]+)/(?<id>\\d+)/(?<tab>[a-z]*)?"` I'd like to have object (after exec):

```
{ 'type' : 'bar', 'id' : 666, 'tab' : 'ifany' }
```

That would be trivial to loop over, now I just can't loop over the properties normally cause there is crap preceding the properties (and even worse, if there is update to XRegExp I might get new crap to skip over in loop).

**Comment by vsimonian** [comment] 2015-09-22 05:31
This issue is a huge show-stopper before I'm able to utilize XRegExp (I don't mean to sound pompous, but it really is a big problem in my use-case).

In the following example, `matches` is, as expected, an array, with built-in array functions, and all the capture data.

```javascript
var regex = XRegExp('(?<cap>[a-z]+)')
var matches = XRegExp.exec('data', regex)
matches.cap === 'data'
```

This becomes problematic when named capture groups coincide with any standard array properties, as the results will override the array property/member.

In this example, the native `slice` function is replaced with the contents of the `slice` named capture group.

```javascript
var regex = XRegExp('(?<slice>[a-z]+)')
var matches = XRegExp.exec('data', regex)
matches.slice === 'data'
```

It simply isn't manageable to have to tiptoe around these names, especially when developing software which exposes XRegExp's functionality outwards in one fashion or another. It's unreasonable to have the expectation that every user will avoid every array property name in their regular expressions. Such arbitrary restrictions reveal a design flaw.

At the very least, there needs to be namespacing, i.e.:

```javascript
var regex = XRegExp('(?<slice>[a-z]+)')
var matches = XRegExp.exec('data', regex)
matches.named.slice === 'data'
```

Also, whatever happened to #51? Is `.names` or an equivalent still planned? It seems an essential feature, yet it isn't implemented as of yet in 3.0.0-pre though the issue is over several years old (and this one is older).

**Comment by vsimonian** [comment] 2015-09-22 06:58
Now that 3.0.0 is released, is there any plan for namespacing capture groups? It would be a breaking change, and 3.1.0, as a minor version update, cannot include breaking changes.

Perhaps, to mitigate against breaking default behaviour, there could be an option that enforces namespaced results.

**Comment by slevithan** [comment] 2015-09-22 07:15
> Is `.names` or an equivalent still planned?

Yes, `.names` or an equivalent is planned for XRegExp 3.1.0.

> Now that 3.0.0 is released, is there any plan for namespacing capture groups?

I'm not convinced that this should change, for the reasons discussed earlier in this thread.

> In this example, the native slice function is replaced with the contents of the slice named capture group.

What's the problem with this? If using named capture, there isn't really a good reason to have an array of backreferences as the match result. What's needed is a backreferences object, and if you use it that way, you should be fine. As discussed above, even if you namespaced the results the only name that could be freed for use in backreference names is `length`. And XRegExp already prevents creating regexes with groups named `length` or `__proto__`.

> It simply isn't manageable to have to tiptoe around these names, especially when developing software which exposes XRegExp's functionality outwards in one fashion or another.

This is more or less a non-issue if you treat the match object as a dictionary, except in cases where you need to programmatically enumerate the backreference keys (which is an edge case in practice since backreference names are basically never created dynamically unless you're building a regex tester). For such edge cases, the current situation is ugly, but can be worked around for now with `captureNames`.

**Comment by vsimonian** [comment] 2015-09-22 07:45
The case I'm running into is specifically that the code I'm writing has no prior knowledge of what the regex looks like. Named and un-named capture groups may be used together (though, admittedly, un-named capture groups are the less-common of the two), and named capture groups need to be iterated through dynamically to provide proper results.

Without namespacing, there's no way for the code to be fully agnostic to the particular regex, as I understand it.

**Comment by slevithan** [comment] 2015-09-22 08:01
Unfortunately that's correct for now, unless you use `captureNames`.

This is easily fixed by adding `.names` though. I cut it from scope for v3.0.0 because that release had already been help up for a long time. But I'd be happy to accept a pull request for `.names` with the following design (copying my local notes for this prop here):

* Add `<regexp>.xregexp.names` to all XRegExps. `names` is an array of 0+ strings holding the names of named capturing groups used by the regex, unlike `captureNames`' interspersed `null`s for unnamed capturing groups and `null` value if there are no named groups. This is technically a non-breaking change because `<regexp>.xregexp.captureNames` is undocumented.
* Rename `captureNames` as `_captures`.
* Ensure a copy of the `names` array is added to regexes copied via `XRegExp(regexp)` and `XRegExp.globalize(regexp)`.
* Ensure that `<regexp>.xregexp.names` is available on the regex passed as the 4th argument to `XRegExp.forEach` callbacks.
* Add tests for all of the above.

**Comment by vsimonian** [comment] 2015-09-22 08:06
`.names` would certainly resolve the problem with agnostically acquiring knowledge of named capture groups, but would it and if it would, how, would it resolve the problem of reliably and agnostically handling both named and unnamed capture groups, if there is potential for array members to be overwritten?

**Comment by slevithan** [comment] 2015-09-22 08:35
There is no potential for numeric array members or `.length` to be overwritten, so you should be able to agnostically operate on unnamed captures. If you want to apply array methods to the unnamed captures and are worried about members like `slice` being overwritten, it's probably easiest to make a copy using `Array.prototype.slice.call` and then working with the copy.

You should also be able to check if `.names.length > 0` to determine if named capture is used at all.

I would generally not recommend mixing named and unnamed capture. You can use flag `n` ("explicit capture mode", which comes from .NET) to drop unnamed capture altogether.

I admit this reveals a design flaw. But my claim is that the design flaw is (or will be) easy to work around, offers convenience and backcompat benefits, and is not an issue in practice for most users.

You can see a comparison of how capture data is accessed with other regex libraries at http://xregexp.com/syntax/named_capture_comparison/

In XRegExp 4.0.0, it might be worthwhile to break backcompat to stop storing named capture properties on the result array, and instead use a `group` object or method to get the captured values.

**Comment by vsimonian** [comment] 2015-09-22 15:23
Making that change would allow me to feel confident in relying on XRegExp. I find it hard to put my faith on code that may overwrite the properties I am using on an array. Namespacing would make the software much more solid and I would be much more comfortable using it in production.

Additionally, `length` is a common term, and it is a very odd restriction to not allow users to have regexes with `length` as a named capture group, even though it may be only one such "reserved" word.

I think the way to handle this in the meantime would be to add namespacing as an option not enabled by default. This would:

- Allow users to entirely bypass the problem of array properties being overwritten
- Allow users to use `length` as a name for a capture group if they so wish
- Avoid breaking changes for everyone else still relying on old functionality

Then, in v4.0.0, namespacing would be default.

**Comment by slevithan** [comment] 2015-09-23 16:57
Thanks for the pull request! I'll come back to it when I have time to carefully review it.

You've convinced me that namespacing (or some other solution for not storing backreferences as own properties on the result array) should be pursued for v4.0.0.

> I think the way to handle this in the meantime would be to add namespacing as an option not enabled by default.

Hmm, this is an interesting suggestion. I wouldn't want to start adding a `group` object to result arrays prior to dropping backreferences as own properties on the result array (since that would require making `group` a new reserved word), but then that is not what you suggested. Perhaps this could be added as an option via `XRegExp.install`/`uninstall`. If it didn't make a big mess of the code to support both ways of doing this, it's certainly something I'd consider supporting in v3.1.0 (especially if you were willing to implement this). But keep in mind that there are probably a lot of non-obvious things that would need to be updated--e.g. match arrays that get passed into replacement functions, named backreferences that get passed forward with `matchChain`, etc.

**Comment by vsimonian** [comment] 2015-09-24 02:21
`install` and its friends were just the pathway I was thinking of for implementing this sort of togglable functionality. That way, you run it once, and are done with it, instead of writing nasty code throughout your use. If someone is going to use namespacing, they will undoubtedly want it in all occasions. At the very least, I certainly would.

---

There are pros and cons to both implementing and avoiding the implementation of `names` if namespacing is the intended goal:

- **Implement `<regexp>.xregexp.names`**
  - Pros:
    - Allows easy access to a dependable list of named capture groups if namespacing is not active.
  - Cons:
    - May discourage people from adopting namespaces by making it easier to delay (inevitable) refactoring
    - Adds another feature that may have its syntax/usage changed in future versions of XRegExp
- **Don't implement `<regexp>.xregexp.names`**
  - Pros:
    - Encourages people to switch to namespacing, which will be the future default behaviour
  - Cons:
    - Does not provide easy listing of named capture groups for users not using namespacing with XRegExp
    - While it may encourage people to switch to namespacing if they are looking for lists of named capture groups, there is no guarantee that the syntax in future versions of XRegExp will be the same anyway. So what is being gained here?

---

From observation alone, it seems that the purpose of constraining all the XRegExp-added extensions to the results array into an `xregexp` property is to avoid adding to the list of reserved names that named capture groups must avoid, a side-effect of not having namespacing. If namespacing is added in a future release and made the default behaviour, then there may not be a need to further complicate the syntax with which to gain access to the functionality that XRegExp exposes in these properties.

So instead of:

```javascript
var regex = XRegExp('(?<length>[0-9]+)')
var matches = XRegExp.exec('123456789', regex)
var data = matches.xregexp.namedGroups.length
```

we could see

```javascript
var regex = XRegExp('(?<length>[0-9]+)')
var matches = XRegExp.exec('123456789', regex)
var data = matches.namedGroups.length
```

or something to that effect.

**Comment by slevithan** [comment] 2015-09-25 05:53
Excellent feedback, thanks. A couple reactions to your pros and cons list:

> Pros: Allows easy access to a dependable list of named capture groups if namespacing is not active.

I think the goal with the "namespaing" option should be to use it as a path toward deprecation of unnamespaced backreferences. So this would only be a short term advantage, until the ability to use unnamespaced backreferences is removed.

> While it may encourage people to switch to namespacing if they are looking for lists of named capture groups, there is no guarantee that the syntax in future versions of XRegExp will be the same anyway. So what is being gained here?

You'd at least gain the advantage of not having to deal with two ways to do the same thing. Also, the hard part is getting the "namespacing" option functional, and working through any initial edge cases and tradeoffs. But once it's fully functional, there's a clear path toward making that the default and removing other options. So although there are no guarantees, I think it's reasonable to make assumptions about APIs in future versions especially if it's documented in advance.

I agree with the others pros and cons on your list, and am leaning toward not adding `<regexp>.xregexp.names`.

In the third section of your comment, in seems like there is some confusion.

> From observation alone, it seems that the purpose of constraining all the XRegExp-added extensions to the results array into an `xregexp` property is to avoid adding to the list of reserved names that named capture groups must avoid

There is no `xregexp` property on result arrays. The `xregexp` property is added to *regexes* created by `XRegExp`, as well as native regexes that are copied or used in various ways with XRegExp methods. So you would never do something like `len = match.xregexp.namedGroups.length`. Instead it would be `len = regex.xregexp.names.length` or `len = Object.keys(match.groups).length`.

**Comment by vsimonian** [comment] 2015-09-25 06:11
Ah, you're absolutely right, I had the two confused on that last point. `namedGroups` was an object in that example, with `length` the capture group result instead of the length of an array of named groups.

So it sounds like we can skip `.names` and move to namespacing via `install`?

**Comment by vsimonian** [comment] 2015-09-25 06:30
For reference, [here's an example](https://github.com/vsimonian/molecular/blob/master/src/route.es6#L52-L68) of how I'm trying to use XRegExp in the context of routing.

**Comment by slevithan** [comment] 2015-09-25 06:31
Ah, gotcha re: your example code with `namedGroups`.

> So it sounds like we can skip `.names` and move to namespacing via `install`?

I think so, yeah. Thanks again for the great idea. I hadn't previously considered using `install` and friends as a clean path for deprecation (for this and any number of other features in the future). Not having a clean deprecation path and a good story around backcompat along the way was probably the biggest reason for not making progress on this earlier.

**Comment by slevithan** [comment] 2017-04-10 07:54
Summarizing the proposed change since this is a long thread to read through:

* Add a new option "namingspacing" to `XRegExp.install`/`uninstall`/`isInstalled`.
* This option is off by default in v3.2 or whenever this is introduced. In v4.0.0 (or whenever), the "namespacing" option will be on by default, and the ability to turn it off might be removed.
* When enabled, named backreferences are added to a `groups` object on result arrays, rather than as own properties.
  * For `String.prototype.replace` replacement functions (where named backreferences are added as properties of the first String argument), maybe leave things as they are (no `groups` object). If https://github.com/tc39/proposal-regexp-named-groups moves beyond the proposal stage, then XRegExp should follow wherever ECMAScript is headed.
* When enabled, `length` and `__proto__` are no longer reserved words for named captures. Using `__proto__` as a capture name will still lead to undesired results, so don’t do that.

**Closed** 2017-04-17 06:51 UTC
Labels: enhancement
